name:                reflex-fltk
version:             0.1.0.0
github:              "MarisaKirisame/reflex-fltk"
license:             BSD3
author:              "Marisa Kirisame"
maintainer:          "lolisa@marisa.moe"
copyright:           "2018 Marisa Kirisame"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/MarisaKirisame/reflex-fltk#readme>

dependencies:
- base >= 4.7 && < 5
- reflex
- reflex-host
- fltkhs
- text
- dlist
- transformers

library:
  source-dirs: src
