name:                reflex-fltk
version:             0.1.0.0
github:              "MarisaKirisame/reflex-fltk"
license:             BSD3
author:              "Marisa Kirisame"
maintainer:          "lolisa@marisa.moe"
copyright:           "2018 Marisa Kirisame"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/MarisaKirisame/reflex-fltk#readme>

dependencies:
- base >= 4.7 && < 5
- reflex
- reflex-host
- fltkhs
- text
- dlist
- transformers
- bytestring
- data-default

library:
  source-dirs: src

executables:
  reflex-fltk-counter:
    main:               Counter.hs
    source-dirs:        demo/counter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflex-fltk
  reflex-fltk-clock:
    main:               Clock.hs
    source-dirs:        demo/clock
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflex-fltk
  reflex-fltk-bitmap:
    main:               Bitmap.hs
    source-dirs:        demo/bitmap
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflex-fltk
  reflex-fltk-double-buffer:
    main:               DoubleBuffer.hs
    source-dirs:        demo/double_buffer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reflex-fltk
