resolver: lts-10.6

packages:
- .
extra-deps: [fltkhs-0.5.4.4]

ghc-options:
  "$everything": -pgml g++ "-optl-Wl,--allow-multiple-definition" "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
